old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        simple:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.simple', type: fanout}
        consistent_hash:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.consistent_hash', type: x-consistent-hash}

    consumers:
        ## requeue to the same queue
        simple:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.simple', type: fanout }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.simple' }
            callback: App\Controller\Amqp\Simple\Consumer
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
        consistent_hash0: &consistentHash
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.consistent_hash', type: x-consistent-hash }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash0', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
        consistent_hash1:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash1', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer1
        consistent_hash2:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash2', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer2
        consistent_hash3:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash3', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer3
        consistent_hash4:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash4', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer4
        consistent_hash5:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash5', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer5
        consistent_hash6:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash6', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer6
        consistent_hash7:
            <<: *consistentHash
            queue_options: { name: 'old_sound_rabbit_mq.consumer.consistent_hash7', routing_key: '32' }
            callback: App\Controller\Amqp\ConsistentHash\Consumer7
